name: mydtm
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  easy_localization: ^3.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.0.5
  connection_notifier: ^1.0.1
  persistent_bottom_nav_bar_v2: ^4.2.8
  dio: ^5.2.1+1
  flutter_pw_validator: ^1.5.0
  image_cropper: ^3.0.2
  image_picker: ^0.8.7+3
  awesome_dialog: ^3.1.0
  carousel_slider: ^4.2.1
  flutter_widget_from_html_core: ^0.10.1
  ntp: ^2.0.0
  easy_pdf_viewer: ^1.0.6
#  pdf_viewer_plugin: ^2.0.1
  cached_network_image: ^3.2.3
  url_launcher: ^6.1.11
  flutter_screen_lock: ^9.0.1
#  pdf: ^3.10.1
  path_provider: ^2.0.15
  flutter_animate: ^4.1.1+1
#  flutter_cached_pdfview: ^0.4.1
#  flutter_downloader: ^1.10.2
#  open_file: ^3.2.1
#  otp_autofill: ^2.1.0
#  local_auth: ^2.1.6
#  get_it: ^7.2.0
#  image_gallery_saver: ^1.7.1
#  permission_handler: ^10.2.0
#  flutter_svg: ^2.0.5


dev_dependencies:

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
#  flutter_native_splash: ^2.2.19
##
#flutter_native_splash:
#  color: "#ffffff"
#  image: "assets/images/gerb.png"

flutter:
  uses-material-design: true
  assets:
   - assets/images/
   - assets/lang/

  fonts:
   - family: Roboto-Medium
     fonts:
     - asset: assets/fonts/Roboto-Medium.ttf
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages