name: mydtm
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 4.5.15+25

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  easy_localization: ^3.0.4
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  provider: ^6.1.1
  connection_notifier: ^2.0.1
  dio: ^5.4.1
  flutter_pw_validator: ^1.6.0
  #  image_cropper: ^5.0.1
  share_plus: ^7.2.2
  image_picker: ^1.0.7
  awesome_dialog: ^3.2.0
  carousel_slider: ^4.2.1
  flutter_widget_from_html_core: ^0.14.11
  font_awesome_flutter: ^10.7.0
  animated_bottom_navigation_bar: ^1.3.3
  face_camera: ^0.0.9
  rive: ^0.12.4
  ntp: ^2.0.0
  date_count_down: ^3.0.0
  flutter_cached_pdfview: ^0.4.2
  cached_network_image: ^3.3.1
  url_launcher: ^6.2.5
  flutter_screen_lock: ^9.0.2
  path_provider: ^2.1.2
  flutter_animate: ^4.5.0
  showcaseview: ^2.0.3
  webview_flutter: ^4.7.0
  webview_flutter_wkwebview: ^3.12.0
  animated_splash_screen: ^1.3.0
  page_transition: ^2.1.0
  #  flutter_shake_animated: ^0.0.5
  qr_flutter: ^4.1.0
  page_animation_transition: ^1.0.0
  flutter_background_service: ^5.0.5
  flutter_background_service_ios: ^5.0.0
  flutter_background_service_android: ^6.2.2
  permission_handler: ^11.3.0
  flutter_local_notifications: ^16.3.2
  web_socket_channel: ^2.4.4
  #  internet_connection_checker_plus: ^2.2.0
  flutter_app_badger: ^1.5.0
  local_auth: ^2.2.0
#  firebase_messaging: ^14.7.16
#  firebase_core: ^2.25.4
#  firebase_core_web: ^2.11.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
#  flutter_native_splash: ^2.3.2
###
#flutter_native_splash:
#  color: "#ffffff"
#  image: "assets/images/logobba.png"

flutter:
  uses-material-design: true
  assets:
   - assets/images/
   - assets/lang/
   - assets/fonts/

  fonts:
   - family: Roboto-Medium
     fonts:
     - asset: assets/fonts/Roboto-Medium.ttf
   - family: Roboto-Medium
     fonts:
       - asset: assets/fonts/Inter-Medium.ttf